version: "3"

services:
  file_server:
    container_name: meme-file-server
    image: halverneus/static-file-server
    restart: ${RESTART_POLICY}
    volumes:
      - ${MEMES_DIR}:/web
    ports:
      - "${FILE_SERVER_PORT}:8080"
    expose:
      - ${FILE_SERVER_PORT}
    environment:
      CORS: 'true'
      SHOW_LISTING: 'false'
      DEBUG: 'false'

  cron_job:
    container_name: meme-job
    image: meme-job
    build: .
    restart: ${RESTART_POLICY}
    volumes:
      - ${MEMES_DIR}:/memes
    environment:
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      HOST_URL: ${HOST_URL}
      POST_MEME_ON_STARTUP: ${POST_MEME_ON_STARTUP}
      POST_CRON: ${POST_CRON}
    depends_on:
      - file_server
