version: "3"

services:
  file_server:
    container_name: slack-meme-file-server
    image: halverneus/static-file-server
    restart: ${RESTART_POLICY}
    volumes:
      - ${MEMES_DIR}:/web
    ports:
      - "${FILE_SERVER_PORT}:8080"
    expose:
      - ${FILE_SERVER_PORT}
    environment:
      CORS: true
      DEBUG: false

  cron_job:
    container_name: slack-meme-job
    image: slack-meme-job
    build: .
    restart: ${RESTART_POLICY}
    environment:
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    depends_on:
      - file_server
